### PR TITLE
Documentation improvements

### LINKED ISSUE #9: Document how to find the id of a list
I just can't figure it out, I'm heading to Trello's docs, but it would be nice to have this in the README.

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #9

### CODE REVIEW

**Comment by zanker** [comment]
Ack I'm sorry, this is something I've not used in a while and didn't get notifications on this. I'm happy to merge this if you want to reopen, but I assume given it's been 2 years it's kind of whatever.

**Comment by greg0ire** [comment]
> whatever

I found this while testing, but I'm not using it either, so indeed, whatever :)

**Comment by zanker** [comment]
Haha alright

**Comment by zanker** [comment]
Thanks!

**Comment by maximevalette** [comment]
I'm using it ;) Thanks!

**Pull request merged**
